Tune Star/Controllers/AdministratorController.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using Tune_Star.BLL.DTO;
using Tune_Star.BLL.Interfaces;
using Tune_Star.Filters;

namespace Tune_Star.Controllers
{
    [Culture]

    public class AdministratorController : Controller
    {

        private readonly IUserService userService;

        public AdministratorController(IUserService userServ)
        {
            userService = userServ;
        }

        public async Task<IActionResult> ApplicationList()
        {
            return View(await userService.GetUsers());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Verify(int userId)
        {
            try
            {
                if (userId == 0)
                {
                    return NotFound();
                }

                UserDTO user = await userService.GetUser((int)userId);
                user.Status = 1;
                await userService.UpdateUser(user);
            }
            catch (ValidationException ex)
            {
                return NotFound(ex.Message);
            }
            return View("ApplicationList", await userService.GetUsers());
        }

        public async Task<IActionResult> Disprove(int userId)
        {
            try
            {
                if (userId == 0)
                {
                    return NotFound();
                }

                await userService.DeleteUser((int)userId);  
                

               
            }
            catch (ValidationException ex)
            {
                return NotFound(ex.Message);
            }
            return View("ApplicationList", await userService.GetUsers());
        }
    }
}

Tune Star/Controllers/SongController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using Tune_Star.BLL.DTO;
using Tune_Star.BLL.Interfaces;
using Tune_Star.Filters;


namespace Tune_Star.Controllers
{
    [Culture]

    public class SongController : Controller
    {
        private readonly ISongService songService;
        private readonly IGenreService genreService;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public SongController(ISongService songServ, IWebHostEnvironment webHostEnvironment, IGenreService genreService)
        {
            songService = songServ;
            _webHostEnvironment = webHostEnvironment;
            this.genreService = genreService;
        }


        public async Task<IActionResult> Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                SongDTO song = await songService.GetSong((int)id);
                return View(song);
            }
            catch (ValidationException ex)
            {
                return NotFound(ex.Message);
            }
        }

        public IActionResult Download(string filePath)
        {
            string webRootPath = _webHostEnvironment.WebRootPath;
            string fileFullPath = Path.Combine(webRootPath, filePath.TrimStart('/'));

            if (System.IO.File.Exists(fileFullPath))
            {
                var fileBytes = System.IO.File.ReadAllBytes(fileFullPath);
                return File(fileBytes, "application/octet-stream", Path.GetFileName(fileFullPath));
            }
            else
            {
                return NotFound();
            }
        }

        public async Task<IActionResult> Create()
        {
            ViewBag.ListTeams = new SelectList(await genreService.GetGenres(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SongDTO song, IFormFile uploadedFile, IFormFile uploadedSong)
        {

            if (ModelState.IsValid)
            {
                string path = "/pictures/" + uploadedFile.FileName;

                using (var fileStream = new FileStream(_webHostEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }

                song.Img = path;

                string songPath = "/music/" + uploadedSong.FileName;

                string songPhysicalPath = _webHostEnvironment.WebRootPath + songPath;

                using (var fileStream = new FileStream(songPhysicalPath, FileMode.Create))
                {
                    await uploadedSong.CopyToAsync(fileStream);
                }

                song.Path = songPath;

                await songService.CreateSong(song);
                return RedirectToAction("Index", "Home");
            }
            ViewBag.ListTeams = new SelectList(await genreService.GetGenres(), "Id", "Name", song.GenreId);
            return View(song);
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                await songService.DeleteSong(id);
                return RedirectToAction("Index", "Home");
            }
            catch (ValidationException ex)
            {
                return NotFound(ex.Message);
            }
        }


    }
}

Tune Star/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tune Star!</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Tune_Star.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Urbanist:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <script>

        var logo1Url = '@Url.Content("~/icons/logo1.png")';
        var logo2Url = '@Url.Content("~/icons/logo2.png")';
        function changeStyleAndImage(state) {
            var tuneStar = document.getElementById('tuneStar');
            var img = document.getElementById('navbar-img');
            if (state === 'hovered') {
                tuneStar.style.color = 'red'; 
                img.src = logo2Url; 
            } else {
                tuneStar.style.color = 'white'; 
                img.src = logo1Url; 
            }
        }
    </script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-#131212 box-shadow mb-3">
            <div class="container-fluid d-flex justify-content-between align-items-center" >
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index" style="display: flex; align-items: center;">
                    <img src="@Url.Content("~/icons/logo1.png")" id="navbar-img" alt="Логотип" style="width: 50px; height: auto;" onmouseover="changeStyleAndImage('hovered')" onmouseout="changeStyleAndImage('normal')">
                    <span id="tuneStar" style="margin-right: 10px;" onmouseover="changeStyleAndImage('hovered')" onmouseout="changeStyleAndImage('normal')">Tune st☆r</span>
                </a>

                @if (Context.Session.GetString("Login") != null)
                {
                    <p class="welcome">Welcome, <b>@Context.Session.GetString("Login") ☆</b>!  </p>
                }

               
                <div class="d-flex align-items-center">
                    @if (Context.Session.GetString("Login") != null)
                    {    
                        @if(Context.Session.GetString("Login") == "admin")
                        {
                            <button class="me-3" onclick="redirectToPanel()">Control Panel</button>
                        }
                        <button class="me-3" onclick="redirectToCreate()">Upload</button>
                        <button class="me-3" onclick="redirectToLogOut()">Logout</button>

                    }
                    else{
                        <button class="me-3" onclick="redirectToLogin()">Sign in</button>
                        <button class="me-3" onclick="redirectToRegister()">Create Account</button>
                    }
                  
                </div>

                <script>
                    function redirectToRegister() {
                        window.location.href = '@Url.Action("Register", "Users")';
                    }
                    function redirectToLogin() {
                        window.location.href = '@Url.Action("Login", "Users")';
                    }
                    function redirectToLogOut() {
                        window.location.href = '@Url.Action("Logout", "Home")';
                    }
                    function redirectToPanel() {
                        window.location.href = '@Url.Action("ApplicationList", "Administrator")';
                    }
                    function redirectToCreate() {
                        window.location.href = '@Url.Action("Create", "Song")';
                    }

                </script>
            </div>


                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                   
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>